import dns from "node:dns/promises";
dns.setServers(["8.8.8.8", "8.8.4.4"])

import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "animate.css";

const OutPoppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutPoppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
          <main className="container mx-auto">
                 {children}
          </main>

        <Footer></Footer>
        </body>
    </html>
  );
}
